# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de7499a2878e0145ec051812468dcd4abcef3bf38b12b48653fcdfe625c89ae03940360bb208fbbd9af05fa9901bb140a8d9db1ee33b4aa7a9133b6c8ea9002d

test:
  secret_key_base: 4505cc1a17c1bad8c1278f7b2b909b52d5a2cab0f32da99429c5e6d7779a547969bf9336f56fc092cb38a38c92e0686279fad6200fc3d976da85b43d91561785

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
